<?php

return [

    'categories' => [
        'text' => 'Text & Writing',
        'data' => 'Data & Encoding',
        'numbers' => 'Numbers & Time',
        'generators' => 'Generators',
    ],

    'tools' => [
        [
            'slug' => 'character-counter',
            'name' => 'Character Counter',
            'tagline' => 'Count characters & words.',
            'category' => 'text',
            'icon' => ['type' => 'flux', 'name' => 'hashtag'],
        ],
        [
            'slug' => 'case-converter',
            'name' => 'Case Converter',
            'tagline' => 'camelCase, snake_case, kebab-case & more.',
            'category' => 'text',
            'icon' => ['type' => 'flux', 'name' => 'language'],
        ],
        [
            'slug' => 'diff-viewer',
            'name' => 'Diff Viewer',
            'tagline' => 'Compare two pieces of text.',
            'category' => 'text',
            'icon' => ['type' => 'flux', 'name' => 'arrows-right-left'],
        ],
        [
            'slug' => 'markdown-converter',
            'name' => 'Markdown Converter',
            'tagline' => 'Convert between Markdown & HTML.',
            'category' => 'text',
            'icon' => ['type' => 'flux', 'name' => 'code-bracket-square'],
        ],
        [
            'slug' => 'percentage-calculator',
            'name' => 'Percentage Calculator',
            'tagline' => 'Common percentage calculations.',
            'category' => 'numbers',
            'icon' => ['type' => 'flux', 'name' => 'calculator'],
        ],
        [
            'slug' => 'unit-converter',
            'name' => 'Unit Converter',
            'tagline' => 'Length, weight, temperature & data sizes.',
            'category' => 'numbers',
            'icon' => ['type' => 'flux', 'name' => 'scale'],
        ],
        [
            'slug' => 'timestamp-converter',
            'name' => 'Timestamp Converter',
            'tagline' => 'Unix epoch ↔ ISO ↔ human, with timezones.',
            'category' => 'numbers',
            'icon' => ['type' => 'flux', 'name' => 'clock'],
        ],
        [
            'slug' => 'barcode-generator',
            'name' => 'Barcode Generator',
            'tagline' => 'Generate & print Code 128 barcodes.',
            'category' => 'generators',
            'icon' => ['type' => 'flux', 'name' => 'tag'],
        ],
        [
            'slug' => 'qr-code-generator',
            'name' => 'QR Code Generator',
            'tagline' => 'Generate QR codes for URLs, text, and more.',
            'category' => 'generators',
            'icon' => ['type' => 'flux', 'name' => 'qr-code'],
        ],
        [
            'slug' => 'base64-encoder',
            'name' => 'Base64 Encoder',
            'tagline' => 'Encode & decode Base64 for text or files.',
            'category' => 'data',
            'icon' => ['type' => 'flux', 'name' => 'arrows-right-left'],
        ],
        [
            'slug' => 'url-encoder',
            'name' => 'URL Encoder',
            'tagline' => 'Percent-encode & decode URL components.',
            'category' => 'data',
            'icon' => ['type' => 'flux', 'name' => 'link'],
        ],
        [
            'slug' => 'jwt-decoder',
            'name' => 'JWT Decoder',
            'tagline' => 'Inspect a JWT: header, payload, expiry.',
            'category' => 'data',
            'icon' => ['type' => 'flux', 'name' => 'key'],
        ],
        [
            'slug' => 'hash-generator',
            'name' => 'Hash Generator',
            'tagline' => 'MD5, SHA-1, SHA-256 & SHA-512 for text or file.',
            'category' => 'data',
            'icon' => ['type' => 'flux', 'name' => 'finger-print'],
        ],
        [
            'slug' => 'color-converter',
            'name' => 'Color Converter',
            'tagline' => 'HEX ↔ RGB ↔ HSL with a contrast checker.',
            'category' => 'data',
            'icon' => ['type' => 'flux', 'name' => 'swatch'],
        ],
        [
            'slug' => 'json-formatter',
            'name' => 'JSON Formatter',
            'tagline' => 'Pretty-print, minify, and validate JSON.',
            'category' => 'data',
            'icon' => ['type' => 'flux', 'name' => 'code-bracket'],
        ],
        [
            'slug' => 'regex-tester',
            'name' => 'Regex Tester',
            'tagline' => 'Build and debug regular expressions.',
            'category' => 'data',
            'icon' => ['type' => 'flux', 'name' => 'magnifying-glass'],
        ],
        [
            'slug' => 'password-generator',
            'name' => 'Password Generator',
            'tagline' => 'Strong, random passwords with a strength meter.',
            'category' => 'generators',
            'icon' => ['type' => 'flux', 'name' => 'lock-closed'],
        ],
        [
            'slug' => 'uuid-generator',
            'name' => 'UUID Generator',
            'tagline' => 'Generate v4 or v7 UUIDs in bulk.',
            'category' => 'generators',
            'icon' => ['type' => 'flux', 'name' => 'identification'],
        ],
        [
            'slug' => 'image-resizer',
            'name' => 'Image Resizer',
            'tagline' => 'Resize, convert & build favicons in your browser.',
            'category' => 'generators',
            'icon' => ['type' => 'flux', 'name' => 'photo'],
        ],
        [
            'slug' => 'slug-generator',
            'name' => 'Slug Generator',
            'tagline' => 'Turn any string into a URL slug.',
            'category' => 'generators',
            'icon' => ['type' => 'flux', 'name' => 'link'],
        ],
        [
            'slug' => 'lorem-ipsum',
            'name' => 'Lorem Ipsum',
            'tagline' => 'Generate placeholder text.',
            'category' => 'generators',
            'icon' => ['type' => 'flux', 'name' => 'document-text'],
        ],
    ],

];
