<?php

return [

    'site' => [
        'name' => 'Savvy Goose',
        'tagline' => 'Free Online Tools, No Sign-up',
        'description' => 'A small kit of online tools for everyday work: barcode and QR generators, JSON formatter, percentage calculator, and more. No sign-up.',
        'og_image' => '/image/og.jpg',
    ],

    'categories' => [
        'text' => 'Text & Writing',
        'data' => 'Data & Encoding',
        'numbers' => 'Numbers & Time',
        'generators' => 'Generators',
        'diagrams' => 'Diagrams',
        'dev' => 'Developer Tools',
    ],

    'category_seo' => [
        'text' => [
            'title' => 'Text & Writing Tools',
            'description' => 'Tools for working with text: character counter, case converter, diff viewer, and a Markdown to HTML converter. All run in your browser.',
        ],
        'data' => [
            'title' => 'Data & Encoding Tools',
            'description' => 'Encoders, decoders, and formatters for the things you reach for daily: Base64, URLs, JWTs, hashes, JSON, regex, and more.',
        ],
        'numbers' => [
            'title' => 'Number & Time Tools',
            'description' => 'Quick calculators: percentages, unit conversions, Unix timestamps, and the time between two dates.',
        ],
        'generators' => [
            'title' => 'Generators',
            'description' => 'Generators for barcodes, QR codes, passwords, UUIDs, URL slugs, and Lorem Ipsum placeholder text.',
        ],
        'diagrams' => [
            'title' => 'Diagram Tools',
            'description' => 'Turn plain text into diagrams. Write Mermaid syntax, preview it live, and export the result as SVG or PNG.',
        ],
        'dev' => [
            'title' => 'Developer Tools',
            'description' => 'Tools for everyday developer chores: build and explain cron schedules, or resolve and star the GitHub repos behind your dependencies.',
        ],
    ],

    'tools' => [
        [
            'slug' => 'character-counter',
            'name' => 'Character Counter',
            'tagline' => 'Count characters & words.',
            'category' => 'text',
            'icon' => ['type' => 'flux', 'name' => 'hashtag'],
            'meta' => [
                'title' => 'Character & Word Counter',
                'description' => 'Counts characters, words, sentences, and reading time as you type. Free, no sign-up, runs in your browser.',
            ],
            'howto' => [
                'Paste or type text into the editor.',
                'Counts for characters, words, sentences, lines, and reading time update as you go.',
                'Use the Copy button to grab your text, or Clear to start over.',
            ],
            'faqs' => [
                ['q' => 'How are characters counted?', 'a' => 'Every Unicode code point counts as one character, including spaces and line breaks. There\'s a separate count that excludes whitespace, so you can count characters in a string with or without spaces.'],
                ['q' => 'What are common character limits?', 'a' => 'A few worth knowing: X/Twitter posts are 280 characters, a single SMS is 160, a meta description shows about 155 to 160, and an SEO title tag is around 60. The live count makes it easy to stay under any of them.'],
                ['q' => 'How is reading time estimated?', 'a' => 'Reading time assumes 200 words per minute, the average for adult silent reading.'],
                ['q' => 'Is my text uploaded anywhere?', 'a' => 'No. Counting runs in your browser, so your text never leaves your device.'],
            ],
        ],
        [
            'slug' => 'case-converter',
            'name' => 'Case Converter',
            'tagline' => 'camelCase, snake_case, kebab-case & more.',
            'category' => 'text',
            'icon' => ['type' => 'flux', 'name' => 'language'],
            'related' => ['slug-generator', 'character-counter'],
            'meta' => [
                'title' => 'Case Converter: camelCase, snake_case & more',
                'description' => 'Converts text between camelCase, snake_case, kebab-case, PascalCase, Title Case, UPPER, and lower. Instant, browser-only.',
            ],
            'howto' => [
                'Enter or paste your text.',
                'Pick the case format you want.',
                'Copy the converted text with one click.',
            ],
            'faqs' => [
                ['q' => 'Which cases are supported?', 'a' => 'camelCase, PascalCase, snake_case, SCREAMING_SNAKE_CASE, kebab-case, Title Case, sentence case, UPPER, and lower.'],
                ['q' => 'How do I convert a string to camelCase?', 'a' => 'Paste your text and read the camelCase row. Words are joined with no spaces, the first word is lowercase, and each following word is capitalised, so "user profile id" becomes "userProfileId".'],
                ['q' => 'What is the difference between camelCase and PascalCase?', 'a' => 'Both remove spaces and capitalise each word. camelCase leaves the very first letter lowercase (userProfileId), while PascalCase capitalises it too (UserProfileId).'],
                ['q' => 'How do I reverse camelCase back into words?', 'a' => 'Paste the camelCase (or PascalCase) string and pick sentence case or Title Case. The converter splits on the capital-letter boundaries, so "userProfileId" becomes "User Profile Id".'],
                ['q' => 'Does it handle non-English text?', 'a' => 'Unicode letters are preserved, and diacritics are kept rather than stripped.'],
                ['q' => 'Is my text sent anywhere?', 'a' => 'No. The conversion runs locally.'],
            ],
        ],
        [
            'slug' => 'diff-viewer',
            'name' => 'Diff Viewer',
            'tagline' => 'Compare two pieces of text.',
            'category' => 'text',
            'icon' => ['type' => 'flux', 'name' => 'arrows-right-left'],
            'meta' => [
                'title' => 'Text Diff Viewer: Compare Two Texts',
                'description' => 'Drop in two pieces of text and see what changed. Additions, deletions, and edited lines are called out side-by-side.',
            ],
            'howto' => [
                'Paste the original text on the left.',
                'Paste the changed version on the right.',
                'Additions and deletions are highlighted line-by-line.',
            ],
            'faqs' => [
                ['q' => 'How is the diff computed?', 'a' => 'It\'s a line-based diff that runs locally. Lines that only differ slightly are still highlighted as changed.'],
                ['q' => 'Can I diff long files?', 'a' => 'There\'s no hard limit, but very large inputs can slow the browser down.'],
                ['q' => 'Is my text uploaded?', 'a' => 'No. Both inputs stay in your browser.'],
            ],
        ],
        [
            'slug' => 'markdown-converter',
            'name' => 'Markdown Converter',
            'tagline' => 'Convert between Markdown & HTML.',
            'category' => 'text',
            'icon' => ['type' => 'flux', 'name' => 'code-bracket-square'],
            'meta' => [
                'title' => 'Markdown to HTML Converter',
                'description' => 'Convert Markdown to HTML and HTML back to Markdown. CommonMark-compatible with GitHub-flavored extensions.',
            ],
            'howto' => [
                'Paste Markdown or HTML into the editor.',
                'Switch direction to convert either way.',
                'Copy the converted output.',
            ],
            'faqs' => [
                ['q' => 'Which Markdown flavor is supported?', 'a' => 'CommonMark with GitHub-flavored extensions, including tables and fenced code blocks.'],
                ['q' => 'Does it support tables?', 'a' => 'GFM tables convert in both directions.'],
                ['q' => 'Is my content sent to a server?', 'a' => 'No. The conversion happens locally in your browser.'],
            ],
        ],
        [
            'slug' => 'percentage-calculator',
            'name' => 'Percentage Calculator',
            'tagline' => 'Common percentage calculations.',
            'category' => 'numbers',
            'icon' => ['type' => 'flux', 'name' => 'calculator'],
            'meta' => [
                'title' => 'Percentage Calculator',
                'description' => 'Covers the percentage questions you actually run into: percent of a number, percent change, percent of total, discounts, and tips.',
            ],
            'howto' => [
                'Pick the percentage operation you need.',
                'Enter the values. The result updates as you type.',
                'Copy any result with one click.',
            ],
            'faqs' => [
                ['q' => 'What can it calculate?', 'a' => 'Five things: what X% of a number is, what percent one number is of another, the percent change between two numbers, the reverse (a number is X% of what), and adding or subtracting a percentage for tax, tip, markup, or discount.'],
                ['q' => 'Is the calculation private?', 'a' => 'Yes. Everything runs locally in your browser.'],
            ],
        ],
        [
            'slug' => 'unit-converter',
            'name' => 'Unit Converter',
            'tagline' => 'Length, weight, temperature, volume & data sizes.',
            'category' => 'numbers',
            'icon' => ['type' => 'flux', 'name' => 'scale'],
            'meta' => [
                'title' => 'Unit Converter: Length, Weight, Temp, Volume, Data',
                'description' => 'Convert between metric and imperial units. Covers length, weight, temperature, volume, and digital data sizes.',
            ],
            'howto' => [
                'Pick a unit category (length, weight, etc.).',
                'Choose the source and target units.',
                'Type a value. The conversion updates live.',
            ],
            'faqs' => [
                ['q' => 'Which categories are supported?', 'a' => 'Length, weight/mass, temperature, volume, and digital data sizes (bytes through terabytes).'],
                ['q' => 'How precise are the conversions?', 'a' => 'Conversions use standard SI factors with high-precision floating point.'],
            ],
        ],
        [
            'slug' => 'timestamp-converter',
            'name' => 'Timestamp Converter',
            'tagline' => 'Unix epoch ↔ ISO ↔ human, with timezones.',
            'category' => 'numbers',
            'icon' => ['type' => 'flux', 'name' => 'clock'],
            'meta' => [
                'title' => 'Unix Timestamp Converter (Epoch ↔ ISO ↔ Human)',
                'description' => 'Convert Unix timestamps to ISO 8601 and human-readable dates, or back the other way. Handles timezones, seconds, and milliseconds.',
            ],
            'howto' => [
                'Paste a Unix timestamp (seconds or milliseconds), or pick a date.',
                'Adjust the timezone if needed.',
                'Copy the format you need: Unix, ISO 8601, RFC 2822, or human-readable.',
            ],
            'faqs' => [
                ['q' => 'How do I convert a Unix timestamp to a date?', 'a' => 'Paste the timestamp and the date appears as ISO 8601 (UTC), a zoned ISO string, RFC 2822, and a human-readable date, all at once.'],
                ['q' => 'How do I convert ISO 8601 to a Unix timestamp?', 'a' => 'Paste an ISO 8601 string like 2026-01-15T09:30:00Z and the Unix timestamp appears in both seconds and milliseconds.'],
                ['q' => 'How do I convert epoch to ISO 8601?', 'a' => 'Enter the epoch (Unix) value and read the ISO 8601 (UTC) row. Epoch 0 is 1970-01-01T00:00:00Z, the moment Unix time starts counting.'],
                ['q' => 'How do I convert a timestamp to my timezone (IST, PST, GMT)?', 'a' => 'Pick any IANA timezone (for example Asia/Kolkata for IST, America/Los_Angeles for PST, or UTC for GMT) and the zoned outputs update instantly.'],
                ['q' => 'What is ISO 8601 format?', 'a' => 'ISO 8601 writes dates as YYYY-MM-DDThh:mm:ss followed by a timezone: Z for UTC, or an offset like +05:30. It sorts chronologically as plain text, which is why it is the default for logs and APIs.'],
                ['q' => 'Does it support milliseconds?', 'a' => 'Yes. Seconds, milliseconds, microseconds, and nanoseconds are detected automatically from the magnitude of the number you paste.'],
            ],
        ],
        [
            'slug' => 'time-between-dates',
            'name' => 'Time Between Dates',
            'tagline' => 'Calendar days, business days & holidays between two dates.',
            'category' => 'numbers',
            'icon' => ['type' => 'flux', 'name' => 'calendar-days'],
            'meta' => [
                'title' => 'Time Between Dates: Calendar, Business Days & Holidays',
                'description' => 'Counts days, weeks, business days, and country-specific public holidays between two dates.',
            ],
            'howto' => [
                'Pick a start and end date.',
                'Optionally pick a country to count public holidays.',
                'See calendar days, weekdays, business days, and the list of holidays in range.',
            ],
            'faqs' => [
                ['q' => 'How are business days counted?', 'a' => 'Business days exclude weekends. If you pick a country, public holidays falling on weekdays are also excluded.'],
                ['q' => 'Which countries are supported for holidays?', 'a' => 'A growing list. Open the dropdown to see whether yours is in there.'],
            ],
        ],
        [
            'slug' => 'barcode-generator',
            'name' => 'Barcode Generator',
            'tagline' => 'Generate & print Code 128 barcodes.',
            'category' => 'generators',
            'icon' => ['type' => 'flux', 'name' => 'tag'],
            'meta' => [
                'title' => 'Code 128 Barcode Generator: Print & Share',
                'description' => 'Generates Code 128 barcodes you can print straight from the page, or share by URL. No sign-up, works on mobile.',
            ],
            'howto' => [
                'Type the value you want to encode.',
                'Adjust the size and label as needed.',
                'Hit Print, or copy the share URL. Opening it later restores the same barcode.',
            ],
            'faqs' => [
                ['q' => 'How do I turn text into a barcode?', 'a' => 'Type your text or number into the Value field and the Code 128 barcode updates instantly. Any printable ASCII works: letters, digits, and common punctuation.'],
                ['q' => 'What is a Code 128 barcode?', 'a' => 'Code 128 is a high-density 1D barcode used across shipping, inventory, and warehousing. It encodes the full ASCII set and packs more characters into less width than older symbologies like Code 39.'],
                ['q' => 'Can I copy and paste a barcode?', 'a' => 'A barcode is an image rather than text, so there is nothing to paste into a cell. Use Print to send it straight to a printer or a PDF, or take a screenshot of the preview to drop into another document.'],
                ['q' => 'What is the difference between Code 128 and Code 39?', 'a' => 'Code 39 only handles uppercase letters, digits, and a few symbols, and produces wider barcodes. Code 128 covers the full ASCII set (including lowercase) and is denser, which is why it has largely replaced Code 39 in logistics.'],
                ['q' => 'How is Code 128 different from EAN-13 or UPC?', 'a' => 'EAN-13 and UPC-A are fixed-length retail product codes tied to a global numbering system. Code 128 is general purpose: encode any text or number you like, at any length.'],
                ['q' => 'What are the Code 128 subsets (A, B, and C)?', 'a' => 'Subset A covers uppercase and control characters, B covers upper and lowercase plus symbols, and C packs pairs of digits for compact numeric codes. The encoder picks and switches subsets for you to keep the barcode as short as possible.'],
                ['q' => 'Why won\'t my barcode scan?', 'a' => 'The usual culprits are too little quiet zone (white space) around the bars, low print contrast, or printing too small. Keep a clear margin, print in solid black on white, and increase the size if a scanner struggles.'],
                ['q' => 'What size or DPI should I print at?', 'a' => 'Aim for at least 300 DPI so the bars stay crisp. If a handheld scanner has trouble, widen the sticker rather than cramming the same barcode smaller.'],
                ['q' => 'Can I share a barcode by link?', 'a' => 'Settings are stored in the URL, so opening the link reproduces the exact same barcode. Add ?print=true to the link to auto-open the print dialog.'],
                ['q' => 'Does the value leave my device?', 'a' => 'No. The barcode is rendered in your browser, so whatever you encode stays local.'],
            ],
        ],
        [
            'slug' => 'qr-code-generator',
            'name' => 'QR Code Generator',
            'tagline' => 'Generate QR codes for URLs, text, and more.',
            'category' => 'generators',
            'icon' => ['type' => 'flux', 'name' => 'qr-code'],
            'meta' => [
                'title' => 'QR Code Generator (Free, No Sign-up)',
                'description' => 'Make QR codes for URLs, text, Wi-Fi credentials, or contacts, and download them as PNGs. No sign-up.',
            ],
            'howto' => [
                'Enter the URL or text you want to encode.',
                'Adjust size and error correction if needed.',
                'Download the QR code as a PNG.',
            ],
            'faqs' => [
                ['q' => 'Is there a size or character limit?', 'a' => 'QR codes have a maximum capacity that depends on the error correction level you pick. Plain ASCII fits the most.'],
                ['q' => 'Will it work for Wi-Fi credentials?', 'a' => 'Encode a Wi-Fi connection string and a phone\'s camera will offer to join the network.'],
                ['q' => 'Is data sent to a server?', 'a' => 'No. QR codes are generated locally in your browser.'],
            ],
        ],
        [
            'slug' => 'base64-encoder',
            'name' => 'Base64 Encoder',
            'tagline' => 'Encode & decode Base64 for text or files.',
            'category' => 'data',
            'icon' => ['type' => 'flux', 'name' => 'arrows-right-left'],
            'meta' => [
                'title' => 'Base64 Encoder & Decoder (Text and Files)',
                'description' => 'Encode and decode Base64 for text or files. Everything happens locally, so the input never leaves your device.',
            ],
            'howto' => [
                'Pick text or file mode.',
                'Type or upload your input.',
                'Copy the encoded or decoded output.',
            ],
            'faqs' => [
                ['q' => 'Is URL-safe Base64 supported?', 'a' => 'Yes. Flip the URL-safe toggle if you need it for query strings or filenames.'],
                ['q' => 'Are files uploaded to a server?', 'a' => 'No. Files are read and encoded right in your browser.'],
            ],
        ],
        [
            'slug' => 'image-to-base64',
            'name' => 'Image to Base64',
            'tagline' => 'Convert an image to a Base64 data URI.',
            'category' => 'data',
            'icon' => ['type' => 'flux', 'name' => 'photo'],
            'related' => ['base64-encoder', 'image-resizer', 'hash-generator'],
            'meta' => [
                'title' => 'Image to Base64 Converter (Data URI)',
                'description' => 'Convert PNG, JPEG, GIF, SVG, or WebP images to a Base64 data URI. Copy the raw string, an img tag, or a CSS background. Runs in your browser.',
            ],
            'howto' => [
                'Drop in or pick an image (PNG, JPEG, GIF, SVG, or WebP).',
                'The Base64 data URI is generated instantly, with the size shown.',
                'Copy the raw data URI, a ready-made img tag, or a CSS background rule.',
            ],
            'faqs' => [
                ['q' => 'What is a Base64 data URI?', 'a' => 'A data URI embeds a file directly in text as data:[type];base64,[data]. In HTML or CSS it lets a small image load without a separate network request.'],
                ['q' => 'When should I inline an image as Base64?', 'a' => 'It works best for small, frequently used assets like icons and logos, where saving a request matters. Base64 adds about a third to the byte size, so large photos are better left as normal files.'],
                ['q' => 'Which image formats are supported?', 'a' => 'PNG, JPEG, GIF, SVG, and WebP. The data URI keeps the original format; it does not re-encode the image.'],
                ['q' => 'Is my image uploaded?', 'a' => 'No. The file is read and encoded locally with the browser FileReader, so it never leaves your device.'],
            ],
        ],
        [
            'slug' => 'url-encoder',
            'name' => 'URL Encoder',
            'tagline' => 'Percent-encode & decode URL components.',
            'category' => 'data',
            'icon' => ['type' => 'flux', 'name' => 'link'],
            'related' => ['base64-encoder', 'slug-generator'],
            'meta' => [
                'title' => 'URL Encoder & Decoder (Percent-encode Online)',
                'description' => 'Percent-encode and decode URLs and URL components in the browser. No sign-up.',
            ],
            'howto' => [
                'Paste a URL or component.',
                'Pick component or full-URL encoding.',
                'Copy the encoded or decoded output.',
            ],
            'faqs' => [
                ['q' => 'What\'s the difference between component and full-URL encoding?', 'a' => 'Component encoding (encodeURIComponent) escapes characters like ? and &. Full-URL encoding (encodeURI) leaves URL-structure characters unescaped.'],
            ],
        ],
        [
            'slug' => 'jwt-decoder',
            'name' => 'JWT Decoder',
            'tagline' => 'Inspect a JWT: header, payload, expiry.',
            'category' => 'data',
            'icon' => ['type' => 'flux', 'name' => 'key'],
            'meta' => [
                'title' => 'JWT Decoder: Inspect Header, Payload, Expiry',
                'description' => 'Decode JSON Web Tokens to see the header, payload, and expiry. Tokens stay in your browser.',
            ],
            'howto' => [
                'Paste a JWT.',
                'See the decoded header and payload, plus expiry status.',
            ],
            'faqs' => [
                ['q' => 'Does this verify the signature?', 'a' => 'No, it only decodes the token. Verifying the signature needs the issuer\'s key.'],
                ['q' => 'Are tokens uploaded?', 'a' => 'No. Decoding happens locally, so it\'s safe to paste sensitive tokens.'],
            ],
        ],
        [
            'slug' => 'hash-generator',
            'name' => 'Hash Generator',
            'tagline' => 'MD5, SHA-1, SHA-256 & SHA-512 for text or file.',
            'category' => 'data',
            'icon' => ['type' => 'flux', 'name' => 'finger-print'],
            'meta' => [
                'title' => 'Hash Generator: MD5, SHA-1, SHA-256, SHA-512',
                'description' => 'Hash text or files with MD5, SHA-1, SHA-256, and SHA-512. Runs locally, so nothing is uploaded.',
            ],
            'howto' => [
                'Pick text or file mode.',
                'Type or upload your input.',
                'Copy the hash for any algorithm shown.',
            ],
            'faqs' => [
                ['q' => 'Which algorithms are available?', 'a' => 'MD5, SHA-1, SHA-256, and SHA-512. MD5 and SHA-1 are no longer safe for cryptographic use.'],
                ['q' => 'Are files uploaded?', 'a' => 'No. Files are read locally with the Web Crypto API.'],
            ],
        ],
        [
            'slug' => 'color-converter',
            'name' => 'Color Converter',
            'tagline' => 'HEX ↔ RGB ↔ HSL with a contrast checker.',
            'category' => 'data',
            'icon' => ['type' => 'flux', 'name' => 'swatch'],
            'related' => ['image-resizer'],
            'meta' => [
                'title' => 'Color Converter (HEX ↔ RGB ↔ HSL with Contrast)',
                'description' => 'Convert colors between HEX, RGB, and HSL, and check WCAG contrast ratios between two colors.',
            ],
            'howto' => [
                'Enter a color in any format: HEX, RGB, or HSL.',
                'The equivalents in the other formats appear alongside.',
                'Pair two colors to see the WCAG contrast ratio.',
            ],
            'faqs' => [
                ['q' => 'How do I convert RGB to HEX?', 'a' => 'Type or paste your RGB values and read the HEX field. For example, rgb(37, 99, 235) is #2563EB. You can also paste a full rgb() string into the "Paste any color" box.'],
                ['q' => 'How do I convert HEX to RGB?', 'a' => 'Enter a HEX code and the red, green, and blue channels appear alongside it, along with the HSL equivalent.'],
                ['q' => 'Can I paste an rgb() or hsl() string?', 'a' => 'Yes. The "Paste any color" box accepts hex, rgb(), rgba(), hsl(), hsla(), and named colors like tomato, and fills in the other formats.'],
                ['q' => 'How is contrast measured?', 'a' => 'Using the WCAG 2.1 luminance ratio formula. Pass and fail thresholds for AA and AAA at normal and large text are shown.'],
            ],
        ],
        [
            'slug' => 'json-formatter',
            'name' => 'JSON Formatter',
            'tagline' => 'Pretty-print, minify, and validate JSON.',
            'category' => 'data',
            'icon' => ['type' => 'flux', 'name' => 'code-bracket'],
            'meta' => [
                'title' => 'JSON Formatter: Pretty-print, Minify, Validate',
                'description' => 'Format, prettify, minify, and validate JSON. Pasted JSON stays in your browser, no sign-up.',
            ],
            'howto' => [
                'Paste JSON.',
                'Pick pretty-print or minify.',
                'Errors point at the offending line and column.',
            ],
            'faqs' => [
                ['q' => 'Are comments or trailing commas allowed?', 'a' => 'Strict JSON allows neither. The parser reports the location of the first issue it hits.'],
                ['q' => 'Is my JSON sent to a server?', 'a' => 'No. Parsing and formatting happen in your browser.'],
            ],
        ],
        [
            'slug' => 'format-converter',
            'name' => 'Format Converter',
            'tagline' => 'Convert between JSON, YAML, CSV & XML.',
            'category' => 'data',
            'icon' => ['type' => 'flux', 'name' => 'arrow-path-rounded-square'],
            'meta' => [
                'title' => 'Format Converter: JSON, YAML, CSV, XML',
                'description' => 'Convert data between JSON, YAML, CSV, and XML. Pick a source and target. No sign-up, no upload.',
            ],
            'howto' => [
                'Pick the source format your data is in (JSON, YAML, CSV, or XML).',
                'Pick the target format to convert to.',
                'Paste your data. The converted output appears on the right.',
                'Adjust per-format options as needed: CSV delimiter, XML root element, indent.',
                'Use the swap button to flip the conversion direction without retyping.',
            ],
            'faqs' => [
                ['q' => 'Is my data uploaded anywhere?', 'a' => 'No. The conversion runs in your browser, so nothing is sent to a server.'],
                ['q' => 'How does CSV ↔ JSON work?', 'a' => 'A CSV with a header row becomes an array of objects keyed by column. Going the other way, an array of objects becomes rows, and a single object becomes a one-row CSV.'],
                ['q' => 'How does JSON → XML choose tag names?', 'a' => 'Object keys become element names. The whole document is wrapped in a single root element; you can rename it with the Root field.'],
                ['q' => 'Are XML attributes preserved?', 'a' => 'Yes. Attributes appear in the parsed object with an "@_" prefix and round-trip back to attributes when serialising to XML.'],
                ['q' => 'What about YAML anchors and tags?', 'a' => 'Standard YAML 1.2 features parse correctly. Custom tags and complex anchors may not survive a round trip through other formats.'],
            ],
        ],
        [
            'slug' => 'regex-tester',
            'name' => 'Regex Tester',
            'tagline' => 'Build and debug regular expressions.',
            'category' => 'data',
            'icon' => ['type' => 'flux', 'name' => 'magnifying-glass'],
            'meta' => [
                'title' => 'Regex Tester: Build & Debug Regular Expressions',
                'description' => 'Test JavaScript regular expressions against sample text. Matches and capture groups highlight as you type.',
            ],
            'howto' => [
                'Type a regex and pick flags (g, i, m, s, u, y).',
                'Paste sample text below.',
                'Matches and capture groups highlight live as you type.',
            ],
            'faqs' => [
                ['q' => 'Which regex flavor is supported?', 'a' => 'JavaScript regex (ECMAScript). Lookbehinds and Unicode property escapes work in modern browsers.'],
            ],
        ],
        [
            'slug' => 'browser-info',
            'name' => 'Browser Info',
            'tagline' => 'Viewport, screen size, DPR, browser & OS.',
            'category' => 'data',
            'icon' => ['type' => 'flux', 'name' => 'computer-desktop'],
            'meta' => [
                'title' => 'Browser Info: Viewport, Screen, DPR, Device',
                'description' => 'Shows your viewport size, screen resolution, device pixel ratio, browser, and OS. Handy when debugging responsive layouts.',
            ],
            'howto' => [
                'Open this page on the device you want to inspect.',
                'Resize the window to watch the viewport update live.',
            ],
            'faqs' => [
                ['q' => 'What\'s the difference between viewport and screen size?', 'a' => 'Viewport is the visible area of the page. Screen size is the full physical display, including space outside the browser window.'],
            ],
        ],
        [
            'slug' => 'password-generator',
            'name' => 'Password Generator',
            'tagline' => 'Strong, random passwords with a strength meter.',
            'category' => 'generators',
            'icon' => ['type' => 'flux', 'name' => 'lock-closed'],
            'meta' => [
                'title' => 'Password Generator: Strong & Random',
                'description' => 'Generates strong, random passwords with a built-in strength meter. No sign-up, runs in your browser.',
            ],
            'howto' => [
                'Pick a length and the character classes to include.',
                'Click generate to roll a new password.',
                'Copy with one click.',
            ],
            'faqs' => [
                ['q' => 'How are passwords generated?', 'a' => 'Using the browser\'s cryptographically secure random source (window.crypto). Nothing leaves your device.'],
                ['q' => 'How is strength estimated?', 'a' => 'As bits of entropy: the password length times the log base 2 of the character-set size. It assumes a uniformly random password, which is exactly how these are generated.'],
            ],
        ],
        [
            'slug' => 'passphrase-generator',
            'name' => 'Passphrase Generator',
            'tagline' => 'Memorable, random word-based passphrases.',
            'category' => 'generators',
            'icon' => ['type' => 'flux', 'name' => 'key'],
            'meta' => [
                'title' => 'Passphrase Generator: Random, Memorable',
                'description' => 'Generate Diceware-style passphrases from the EFF large wordlist. Easier to remember than passwords, and just as strong with enough words.',
            ],
            'howto' => [
                'Pick how many words to use and a separator.',
                'Optionally append a digit or symbol for sites that require them.',
                'Hit Regenerate for a new passphrase, then copy.',
            ],
            'faqs' => [
                ['q' => 'Where do the words come from?', 'a' => 'The EFF large wordlist (7,776 words). Each word is picked with the browser\'s cryptographic random source.'],
                ['q' => 'How many words do I need?', 'a' => 'Three words give roughly 38 bits of entropy. Five words gets you past 64 bits, which resists offline cracking. Six or seven is comfortable for high-value accounts.'],
                ['q' => 'Is the passphrase generated on a server?', 'a' => 'No. Word selection runs locally using window.crypto, so nothing leaves your device.'],
            ],
        ],
        [
            'slug' => 'uuid-generator',
            'name' => 'UUID Generator',
            'tagline' => 'Generate v4 or v7 UUIDs in bulk.',
            'category' => 'generators',
            'icon' => ['type' => 'flux', 'name' => 'identification'],
            'meta' => [
                'title' => 'UUID Generator: v4 and v7 in Bulk',
                'description' => 'Generate UUID v4 (random) or v7 (timestamp-ordered) identifiers in bulk, then copy or download the list.',
            ],
            'howto' => [
                'Pick UUID v4 or v7.',
                'Choose how many to generate.',
                'Copy or download the list.',
            ],
            'faqs' => [
                ['q' => 'What\'s the difference between v4 and v7?', 'a' => 'v4 is fully random. v7 prepends a millisecond timestamp so IDs sort chronologically, which is friendlier to database indexes.'],
                ['q' => 'What is a UUID (or GUID)?', 'a' => 'A UUID (Universally Unique Identifier), also called a GUID on Microsoft platforms, is a 128-bit value written as 32 hex digits in five hyphen-separated groups. It identifies something uniquely without a central authority handing out numbers.'],
                ['q' => 'Are UUIDs guaranteed to be unique?', 'a' => 'Not guaranteed, but collisions are astronomically unlikely. A v4 UUID has 122 random bits, so you would need to generate billions per second for many years before a clash became probable.'],
                ['q' => 'Are these generated offline?', 'a' => 'Yes. IDs are created in your browser with window.crypto, so nothing is requested from a server and nothing you generate is logged.'],
                ['q' => 'Does a v7 UUID reveal when it was created?', 'a' => 'Yes. v7 embeds a millisecond timestamp, so the creation time is recoverable from the ID. Use v4 if you need the value to leak nothing about timing.'],
            ],
        ],
        [
            'slug' => 'favicon-generator',
            'name' => 'Favicon Generator',
            'tagline' => 'Turn an image into favicons and a .ico file.',
            'category' => 'generators',
            'icon' => ['type' => 'flux', 'name' => 'sparkles'],
            'related' => ['image-resizer', 'image-to-base64', 'qr-code-generator'],
            'meta' => [
                'title' => 'Favicon Generator: PNG and Multi-size .ico',
                'description' => 'Turn any image into favicons: 16, 32, 48, 180, and 512 px PNGs plus a multi-size favicon.ico, with the HTML to embed them. Runs in your browser.',
            ],
            'howto' => [
                'Drop in or pick an image. A square PNG or SVG gives the sharpest result.',
                'Preview the favicon at every standard size.',
                'Download individual PNGs, the multi-size favicon.ico, and copy the HTML to embed them.',
            ],
            'faqs' => [
                ['q' => 'What image should I use for a favicon?', 'a' => 'A square image works best, ideally 512×512 or larger so the small sizes stay crisp. A transparent PNG or an SVG keeps clean edges. Non-square images are centered and fit without cropping.'],
                ['q' => 'What is the .ico file for?', 'a' => 'favicon.ico is the classic icon browsers look for at your site root. This one bundles 16, 32, and 48 px images in a single file so the browser can pick the size it needs.'],
                ['q' => 'Which sizes do I actually need?', 'a' => 'A favicon.ico plus a 32 px PNG covers most browsers, and a 180 px apple-touch-icon handles iOS home screens. The 192 and 512 px sizes are used by Android and web app manifests.'],
                ['q' => 'How do I add the favicon to my site?', 'a' => 'Put the downloaded files at your site root and paste the generated link tags into your page head. The HTML block on this page is ready to copy.'],
                ['q' => 'Is my image uploaded?', 'a' => 'No. The resizing and .ico packaging happen on a canvas in your browser, so the image never leaves your device.'],
            ],
        ],
        [
            'slug' => 'image-resizer',
            'name' => 'Image Resizer',
            'tagline' => 'Resize and convert images in your browser.',
            'category' => 'generators',
            'icon' => ['type' => 'flux', 'name' => 'photo'],
            'related' => ['color-converter', 'favicon-generator'],
            'meta' => [
                'title' => 'Image Resizer: Resize & Convert PNG, JPEG, WebP',
                'description' => 'Resize images and convert between PNG, JPEG, and WebP. Nothing is uploaded; files stay on your device.',
            ],
            'howto' => [
                'Drop in or pick an image.',
                'Set the target dimensions, position, and rotation.',
                'Pick an output format and download.',
            ],
            'faqs' => [
                ['q' => 'Is my image uploaded?', 'a' => 'No. Resizing and conversion run on a canvas in your browser, so files never leave your device.'],
                ['q' => 'Which output formats are supported?', 'a' => 'PNG, JPEG, and WebP. Pick the format from the dropdown before you download.'],
            ],
        ],
        [
            'slug' => 'slug-generator',
            'name' => 'Slug Generator',
            'tagline' => 'Turn any string into a URL slug.',
            'category' => 'generators',
            'icon' => ['type' => 'flux', 'name' => 'link'],
            'related' => ['case-converter', 'url-encoder'],
            'meta' => [
                'title' => 'Slug Generator: String to URL Slug',
                'description' => 'Turn any string into a URL-friendly slug. Handles diacritics, emoji, and custom separators.',
            ],
            'howto' => [
                'Type or paste the string you want to slugify.',
                'Pick a separator and case style.',
                'Copy the result.',
            ],
            'faqs' => [
                ['q' => 'How do I convert a string to a URL slug?', 'a' => 'Paste your text and it becomes a lowercase, hyphenated slug. "My Blog Post: 10 Things!" turns into "my-blog-post-10-things".'],
                ['q' => 'Should a slug use hyphens or underscores?', 'a' => 'Hyphens. Google treats a hyphen as a word separator but an underscore as a word joiner, so hyphens are the standard for readable, SEO-friendly URLs.'],
                ['q' => 'Are slugs case-sensitive?', 'a' => 'URLs can be, so slugs are lowercased by default to avoid duplicate-address confusion between /My-Page and /my-page.'],
                ['q' => 'How are diacritics handled?', 'a' => 'Diacritics (é, ü, ñ, and so on) are normalized to their ASCII equivalents.'],
                ['q' => 'What about emoji?', 'a' => 'Emoji are stripped, so slugs end up as plain ASCII suitable for URLs.'],
            ],
        ],
        [
            'slug' => 'lorem-ipsum',
            'name' => 'Lorem Ipsum',
            'tagline' => 'Generate placeholder text.',
            'category' => 'generators',
            'icon' => ['type' => 'flux', 'name' => 'document-text'],
            'meta' => [
                'title' => 'Lorem Ipsum Generator: Placeholder Text',
                'description' => 'Generate Lorem Ipsum placeholder text by paragraphs, sentences, or words.',
            ],
            'howto' => [
                'Pick paragraphs, sentences, or words.',
                'Choose how much you need.',
                'Copy with one click.',
            ],
            'faqs' => [
                ['q' => 'Why use Lorem Ipsum?', 'a' => 'It gives you the visual weight of real prose without pulling reviewers into reading the placeholder copy.'],
            ],
        ],
        [
            'slug' => 'mermaid-editor',
            'name' => 'Mermaid Editor',
            'tagline' => 'Write Mermaid, preview live, export SVG or PNG.',
            'category' => 'diagrams',
            'icon' => ['type' => 'flux', 'name' => 'rectangle-group'],
            'meta' => [
                'title' => 'Mermaid Editor: Live Diagram Preview & Export',
                'description' => 'Write Mermaid syntax and watch the diagram render as you type. Pan, zoom, switch themes, and export to SVG or PNG. Nothing is uploaded.',
            ],
            'howto' => [
                'Type or paste Mermaid syntax into the editor, or pick a starter template.',
                'The diagram renders live beside the code. Parse errors point at what went wrong.',
                'Drag to pan and scroll to zoom the preview.',
                'Switch the theme, then export the result as SVG or PNG.',
                'Copy the share URL. Opening it later restores the same diagram.',
            ],
            'faqs' => [
                ['q' => 'Which diagram types are supported?', 'a' => 'Everything Mermaid renders: flowcharts, sequence diagrams, class and state diagrams, entity relationship diagrams, Gantt charts, pie charts, mindmaps, and git graphs.'],
                ['q' => 'Can I share a diagram by link?', 'a' => 'Yes. The source is compressed into the page URL, so the link reproduces your diagram exactly. A very large diagram can outgrow the URL; export the SVG to share those.'],
                ['q' => 'How do I export the diagram?', 'a' => 'Download SVG for crisp vector output that scales to any size, or PNG for pasting into docs and slides. Both render locally.'],
                ['q' => 'Is my diagram sent to a server?', 'a' => 'No. Mermaid runs in your browser, so the source and the rendered diagram never leave your device.'],
            ],
        ],
        [
            'slug' => 'cron-expression-generator',
            'name' => 'Cron Expression Generator',
            'tagline' => 'Build and explain cron schedules, with next run times.',
            'category' => 'dev',
            'icon' => ['type' => 'flux', 'name' => 'clock'],
            'related' => ['timestamp-converter', 'time-between-dates'],
            'meta' => [
                'title' => 'Cron Expression Generator & Explainer',
                'description' => 'Write a cron expression, read it in plain English, and preview the next run times. Presets for the common schedules, all in your browser.',
            ],
            'howto' => [
                'Type a 5-field cron expression, or pick a preset to start.',
                'Read the plain-English description to confirm it does what you meant.',
                'Check the next five run times, then copy the share link.',
            ],
            'faqs' => [
                ['q' => 'What do the five cron fields mean?', 'a' => 'In order: minute (0–59), hour (0–23), day of month (1–31), month (1–12), and day of week (0–6, where 0 and 7 are both Sunday). A star means "every".'],
                ['q' => 'How do I run a job every 5 minutes?', 'a' => 'Use */5 * * * *. The */n syntax means "every n units", so */5 in the minute field fires at 0, 5, 10, and so on.'],
                ['q' => 'How do I schedule weekdays only?', 'a' => 'Put 1-5 in the day-of-week field, for example 0 9 * * 1-5 to run at 9am Monday through Friday.'],
                ['q' => 'What happens if I set both day-of-month and day-of-week?', 'a' => 'Standard cron treats them as OR when both are restricted: the job runs when either condition matches. This tool follows that behaviour when computing the next runs.'],
                ['q' => 'Which timezone are the next runs shown in?', 'a' => 'Your browser\'s local timezone. Cron itself has no timezone; it runs against the clock of whatever machine schedules it.'],
            ],
        ],
        [
            'slug' => 'star-dependencies',
            'name' => 'GitHub Dependency Starrer',
            'tagline' => "Star every GitHub repo behind your project's dependencies.",
            'category' => 'dev',
            'icon' => ['type' => 'flux', 'name' => 'star'],
            'related' => ['cron-expression-generator'],
            'meta' => [
                'title' => 'GitHub Dependency Starrer: Star Your Deps',
                'description' => 'Paste a package.json or composer.json, resolve each dependency to its GitHub repo, and star the ones you pick with one click.',
            ],
            'howto' => [
                'Paste or upload a package.json or composer.json.',
                'Click Resolve dependencies. Each package is matched to a GitHub owner/repo where one exists.',
                'Pick which repos to star, then connect your GitHub account.',
                'Click Star selected. Each repo gets starred with your account, one request per repo.',
            ],
            'faqs' => [
                ['q' => 'Does this need my GitHub password?', 'a' => 'No. It uses GitHub\'s OAuth sign-in. GitHub does not offer a narrower scope for starring, so it requests the "public_repo" scope (access to public repositories) solely to star repos.'],
                ['q' => 'Is anything about my account stored?', 'a' => 'The access token sits in your session for the length of your visit and is never written to a database. Disconnect clears it and revokes the authorization on GitHub\'s side.'],
                ['q' => 'What if a dependency can\'t be resolved?', 'a' => 'Some packages point at a non-GitHub host, a monorepo without a matching repository field, or nothing at all. Those are listed but can\'t be selected.'],
                ['q' => 'Can I star a private repo this way?', 'a' => 'Only public repos. The requested scope deliberately doesn\'t extend to private repositories.'],
            ],
        ],
    ],

];
